easy_admin:
    entities:
#        # List the entity class name you want to manage
#        - App\Entity\Product
        - App\Entity\Message
        - App\Entity\User
    site_name: 'Symfony Chat Dashboard'
