#index:
#    path: /
#    controller: App\Controller\DefaultController::index

# chat:
#     path: /
#     controller: App\Controller\ChatController::index
#     defaults:
#         path: /chat
#         permanent: true

login:
    path: /login
    controller: App\Controller\SecurityController::login